---
title: "covid_plotly"
author: "Mike Jeziorski"
date: "5/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages(c("tidyverse", "plotly"))

library(tidyverse)
library(plotly)
```

Datos del la Secretaría de Salud, Gobierno de México
Fuente de los datos: <https://datos.gob.mx/busca/dataset/informacion-referente-a-casos-covid-19-en-mexico>
Datos crudos: <https://www.gob.mx/salud/documentos/datos-abiertos-152127>

El archivo "qro_raw_210513.csv" contiene los datos para el 13 de mayo de 2021, filtrado para los residentes del estado de Querétaro.

```{r}
qro_raw <- readr::read_csv("qro_raw_210513.csv")
```

```{r, warning=FALSE}
qro_covid_pos <- qro_raw %>%
      
      mutate(sexo = case_when(SEXO == 1 ~ "Mujer",
                              SEXO == 2 ~ "Hombre",
                              SEXO == 99 ~ NA_character_),
             tipo_paciente = case_when(TIPO_PACIENTE == 1 ~ "Ambulatorio",
                                       TIPO_PACIENTE == 2 ~ "Hospitalizado",
                                       TIPO_PACIENTE == 99 ~ NA_character_)) %>%
      filter(RESULTADO_LAB == 1) %>%
      ggplot(aes(x = FECHA_INGRESO, fill = as.factor(tipo_paciente))) +
      geom_bar() +
      labs(x = "Fecha de visita", y = "Total",
           title = "Pacientes positivos en el Edo. de Querétaro (muertos en morado)",
           caption = "Fuente: Dirección General de Epidemiología, Gobierno de México") +
      scale_fill_manual(name = "Tipo de paciente", 
                        labels = c("Ambulatorio", "Hospitalizado"),
                        values = c("blue", "red")) +
      geom_bar(aes(x = FECHA_DEF), fill = "purple") +
      theme_classic()
```

```{r, warning=FALSE}
ggplotly(qro_covid_pos)
```

```{r, warning=FALSE}
def_emb <- filter(qro_raw, RESULTADO_LAB == 1, EMBARAZO == 1, !is.na(FECHA_DEF)) %>%
      nrow()
qro_covid_emb <- qro_raw %>%
      mutate(sexo = case_when(SEXO == 1 ~ "Mujer",
                              SEXO == 2 ~ "Hombre",
                              SEXO == 99 ~ NA_character_),
             tipo_paciente = case_when(TIPO_PACIENTE == 1 ~ "Ambulatorio",
                                       TIPO_PACIENTE == 2 ~ "Hospitalizado",
                                       TIPO_PACIENTE == 99 ~ NA_character_)) %>%
      filter(RESULTADO_LAB == 1, EMBARAZO == 1) %>%
      ggplot(aes(x = FECHA_INGRESO, y = EDAD, color = as.factor(TIPO_PACIENTE))) +
      geom_point() +
      labs(x = "Fecha de ingreso", y = "Edad",
           title = "Mujeres embarazadas positivas para el virus en Edo. de Querétaro",
           subtitle = paste0("Número de defunciones: ", def_emb),
           caption = "Fuente: Dirección General de Epidemiología, Gobierno de México") +
      scale_color_manual(name = "Tipo de paciente", 
                        labels = c("Ambulatoria", "Hospitalizada"),
                        values = c("blue", "red")) +
      ylim(c(0, 50)) +
      theme_classic()
```

```{r}
ggplotly(qro_covid_emb, tooltip = c("FECHA_INGRESO", "EDAD"))
```

