---
title: "penguins_plotly"
author: "Mike Jeziorski"
date: "5/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages(c("tidyverse", "plotly", "palmerpenguins"))

library(tidyverse) # incluye dplyr y ggplot2
library(plotly)
library(palmerpenguins) # juego de datos científicos
```

```{r}
glimpse(penguins)
summary(penguins)
```

```{r}
penguins_hm <- penguins %>%
      filter(!is.na(sex)) %>%
      count(species, island, sex) %>%
      ggplot(aes(x = sex, y = species, fill = n)) +
      geom_tile() +
      facet_grid(~ island) +
      theme_classic() +
      labs(title = "Distribution of penguins")
```

```{r}
ggplotly(penguins_hm)
```

```{r}
penguins_sp <- penguins %>%
      filter(!is.na(sex)) %>%
      ggplot(aes(x = bill_length_mm, y = body_mass_g, shape = sex, color = species, 
                 text = paste0("Sex: ", sex,
                               "\nIsland: ", island,
                               "\nYear: ", year))) +
      geom_point() +
      scale_shape_manual(values = c(1, 16)) +
      labs(x = "Bill length (mm)", y = "Body mass (g)")
```

```{r}
plotly::ggplotly(penguins_sp, tooltip = "text")
```

```{r}
penguins_sp_i <- penguins %>%
   filter(!is.na(sex)) %>%
   plotly::plot_ly(x = ~bill_length_mm, y = ~body_mass_g, color = ~species,
                type = "scatter", mode = "markers")
```


```{r}
# install.packages("htmlwidgets")
library(htmlwidgets)
htmlwidgets::saveWidget(penguins_sp_i, "penguins_scatterplot.html")
```

